"""
Project: Violation Email Reporter
Tool context: Cross-flow sign-off automation
What it does: Generates an HTML email report summarizing all flow violations
and sends it via SMTP. Useful for daily status emails to the design team.
Can be scheduled via cron in CI/CD flows.

Install: pip install (no extra install needed — uses Python built-in smtplib)
Usage:
    python 48_violation_email_reporter.py --dry-run   (preview without sending)
    python 48_violation_email_reporter.py --smtp smtp.company.com --from pd@co.com \
           --to team@co.com,lead@co.com
"""

import smtplib
import argparse
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

# Sample metrics (would be parsed from real reports)
SAMPLE_METRICS = {
    "design":   "soc_top",
    "revision": "RTL_v1.2",
    "date":     datetime.now().strftime("%Y-%m-%d %H:%M"),
    "flows": {
        "Lint":    {"fatal": 0,  "error": 3,  "warning": 15, "status": "IN PROGRESS"},
        "DFT":     {"sa_cov": 98.78, "tr_cov": 95.40, "status": "IN PROGRESS"},
        "CDC":     {"fatal": 1,  "error": 5,  "warning": 8,  "status": "BLOCKED"},
        "RDC":     {"fatal": 0,  "error": 3,  "warning": 2,  "status": "IN PROGRESS"},
        "UPF":     {"iso_miss": 2, "ls_miss": 0, "ret_miss": 1, "status": "IN PROGRESS"},
    },
    "blockers": [
        "CDC: 1 Fatal violation (CDC_GLITCH in clk_ctrl) — must fix before milestone",
        "DFT: Transition coverage 95.4% — target 96%",
        "UPF: 2 missing isolation cells in PD_CPU",
    ],
}

STATUS_COLOR = {
    "PASS":        "#27ae60",
    "IN PROGRESS": "#e67e22",
    "BLOCKED":     "#e74c3c",
    "PENDING":     "#95a5a6",
}


def build_html_email(metrics):
    design = metrics["design"]
    rev    = metrics["revision"]
    date   = metrics["date"]

    flow_rows = ""
    for flow, data in metrics["flows"].items():
        status    = data.get("status", "?")
        status_col= STATUS_COLOR.get(status, "#999")

        if flow == "DFT":
            details = f"SA: {data['sa_cov']}%  TR: {data['tr_cov']}%"
        elif flow == "UPF":
            details = f"ISO miss: {data['iso_miss']}  LS miss: {data['ls_miss']}  RET miss: {data['ret_miss']}"
        else:
            details = f"Fatal: {data.get('fatal',0)}  Error: {data.get('error',0)}  Warn: {data.get('warning',0)}"

        flow_rows += (
            f"<tr><td><strong>{flow}</strong></td><td>{details}</td>"
            f"<td><span style='color:{status_col};font-weight:bold'>{status}</span></td></tr>\n"
        )

    blocker_items = ""
    for b in metrics["blockers"]:
        blocker_items += f"<li style='margin:5px 0;color:#c0392b'>{b}</li>\n"

    html = f"""
<html><body style='font-family:Arial;margin:0;padding:20px;background:#f5f5f5'>
<div style='max-width:700px;margin:auto;background:#fff;border-radius:8px;
            box-shadow:0 2px 8px rgba(0,0,0,.1);overflow:hidden'>
  <div style='background:#1a252f;color:#fff;padding:20px 25px'>
    <h2 style='margin:0'>Sign-Off Status: {design}</h2>
    <p style='margin:5px 0;opacity:.8'>Revision: {rev}  |  {date}</p>
  </div>
  <div style='padding:25px'>
    <h3 style='color:#2c3e50'>Flow Status Summary</h3>
    <table style='width:100%;border-collapse:collapse'>
      <tr style='background:#34495e;color:#fff'>
        <th style='padding:10px;text-align:left'>Flow</th>
        <th style='padding:10px;text-align:left'>Current State</th>
        <th style='padding:10px;text-align:left'>Status</th>
      </tr>
      {flow_rows}
    </table>

    <h3 style='color:#c0392b;margin-top:25px'>Open Blockers</h3>
    <ul style='padding-left:20px'>
      {blocker_items}
    </ul>

    <p style='color:#777;font-size:12px;margin-top:20px;border-top:1px solid #eee;padding-top:10px'>
      Auto-generated by PD sign-off automation. Do not reply to this email.
    </p>
  </div>
</div>
</body></html>"""
    return html


def send_email(html, smtp_server, from_addr, to_addrs, subject):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = from_addr
    msg["To"]      = ", ".join(to_addrs)
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(smtp_server, 25) as server:
            server.sendmail(from_addr, to_addrs, msg.as_string())
        print(f"Email sent to: {', '.join(to_addrs)}")
    except Exception as e:
        print(f"Failed to send email: {e}")
        print("(Use --dry-run to preview without sending)")


# ── Main ─────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Send HTML violation status email")
parser.add_argument("--dry-run",  action="store_true", help="Preview HTML without sending")
parser.add_argument("--smtp",     default="smtp.company.com")
parser.add_argument("--from",     dest="from_addr", default="pd-auto@company.com")
parser.add_argument("--to",       default="pd-team@company.com",
                    help="Comma-separated recipient list")
args = parser.parse_args()

metrics  = SAMPLE_METRICS
html     = build_html_email(metrics)
subject  = (f"[{metrics['design']}] Sign-Off Status — "
            f"{metrics['date'].split()[0]}")

if args.dry_run:
    output = "email_preview.html"
    with open(output, "w") as f:
        f.write(html)
    print(f"Dry-run: email preview saved to {output}")
    print(f"Subject: {subject}")
    print(f"To: {args.to}")
else:
    to_list = [t.strip() for t in args.to.split(",")]
    send_email(html, args.smtp, args.from_addr, to_list, subject)
